AllCops:
  Exclude:
    - 'bin/**/*'

Metrics/AbcSize:
  Max: 30

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false
